# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('valid', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='levels',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=10)),
                ('valid', models.BooleanField(default=True)),
                ('features', models.ManyToManyField(to='default_app.features')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='auth',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.levels'),
        ),
    ]
